In [ ]:
import numpy as np
from numba import jit

In [ ]:
@jit(nopython=True)
def perm_bbfg(M):  # pragma: no cover
    """
    Returns the permanent of a matrix using the bbfg formula in Gray ordering
    The code is a re-implementation from a Python 2 code found in
    `Permanent code golf
    <https://codegolf.stackexchange.com/questions/97060/calculate-the-permanent-as-quickly-as-possible>`_
    using Numba.
    Args:
        M (array) : a square array.
    Returns:
        float or complex: the permanent of a matrix ``M``
    """

    n = len(M)
    if n == 0:
        return M.dtype.type(1.0)
    row_comb = np.sum(M, 0)
    total = 0
    old_gray = 0
    sign = +1
    binary_power_dict = np.array([2**i for i in range(n)])
    num_loops = 2 ** (n - 1)
    for bin_index in range(1, num_loops + 1):
        reduced = np.prod(row_comb)
        total += sign * reduced
        new_gray = bin_index ^ (bin_index // 2)
        gray_diff = old_gray ^ new_gray
        gray_diff_index = np.searchsorted(binary_power_dict,gray_diff)
        new_vector = M[gray_diff_index]
        direction = 2 * ((old_gray > new_gray) - (old_gray < new_gray))
        for i in range(n):
            row_comb[i] += new_vector[i] * direction
        sign = -sign
        old_gray = new_gray
    return total / num_loops

In [ ]:
#for i in range(11):
#  print(i,perm_bbfg(np.ones((i,i),dtype=np.float64)))

In [ ]:
#for i in range(11):
#  print(i,perm_bbfg(np.eye(i,dtype=np.float64)))

In [ ]:
for i in range(6):
  tmp = 0.5*np.eye(i,dtype=np.float64)
  tmp = np.block([[tmp,tmp],[tmp,tmp]])
  print(tmp)
  print(i,perm_bbfg(tmp),2**(-i))

[]
0 1.0 1
[[0.5 0.5]
 [0.5 0.5]]
1 0.5 0.5
[[0.5 0.  0.5 0. ]
 [0.  0.5 0.  0.5]
 [0.5 0.  0.5 0. ]
 [0.  0.5 0.  0.5]]
2 0.25 0.25
[[0.5 0.  0.  0.5 0.  0. ]
 [0.  0.5 0.  0.  0.5 0. ]
 [0.  0.  0.5 0.  0.  0.5]
 [0.5 0.  0.  0.5 0.  0. ]
 [0.  0.5 0.  0.  0.5 0. ]
 [0.  0.  0.5 0.  0.  0.5]]
3 0.125 0.125
[[0.5 0.  0.  0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.5 0.  0.  0.  0.5]
 [0.5 0.  0.  0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.5 0.  0.  0.  0.5]]
4 0.0625 0.0625
[[0.5 0.  0.  0.  0.  0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0.  0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5 0.  0.  0.  0.  0.5]
 [0.5 0.  0.  0.  0.  0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0.  0.  0.  0.  0.5 0. ]
 [0.  